/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mailspammer;

import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import java.awt.*;
import java.awt.event.*;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.*;

/**
 *
 * @author arseniy tsinzerling
 */

public class MailApp extends javax.swing.JFrame {
    
    
//    public static int ii = 0;
    
    
    public MailApp() {
        initComponents();
        jButton1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
//        jButton2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));


        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Number = new javax.swing.JTextField();
        EmailArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SubjectField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        MessageArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        MessageArea2 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SubjectField3 = new javax.swing.JTextField();
        SubjectField4 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        CommentaryLabel3 = new javax.swing.JLabel();
        CommentaryLabel4 = new javax.swing.JLabel();
        CommentaryLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 550));
        setPreferredSize(new java.awt.Dimension(1300, 550));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(100000, 1000000));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 700));
        jPanel1.setLayout(null);

        Number.setText("1");
        jPanel1.add(Number);
        Number.setBounds(200, 270, 90, 30);

        EmailArea.setColumns(20);
        EmailArea.setRows(5);
        jPanel1.add(EmailArea);
        EmailArea.setBounds(200, 10, 320, 90);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Emails listed:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 10, 90, 20);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Repeating String in the message:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(590, 150, 200, 14);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Your spam was sucessfully sent");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 320, 170, 20);

        jButton1.setBackground(new java.awt.Color(255, 108, 108));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("SEND YOUR SPAM");
        jButton1.setBorderPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 400, 260, 60);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Message:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 150, 80, 20);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("How many times to send the spam:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(-30, 270, 210, 20);

        jLabel8.setText("times");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(240, 320, 60, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("0");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 320, 60, 20);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Subject of the email:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 120, 120, 14);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Sender email password:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(850, 80, 160, 14);
        jPanel1.add(SubjectField1);
        SubjectField1.setBounds(200, 110, 370, 30);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(50, 20));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(50, 20));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(50, 20));

        MessageArea1.setColumns(20);
        MessageArea1.setRows(5);
        jScrollPane2.setViewportView(MessageArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(200, 140, 370, 120);

        jScrollPane3.setMaximumSize(new java.awt.Dimension(50, 16));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(50, 16));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(50, 16));

        MessageArea2.setColumns(20);
        MessageArea2.setRows(3);
        jScrollPane3.setViewportView(MessageArea2);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(590, 170, 220, 90);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Repeating String in the subject:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(590, 90, 200, 14);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Sender email:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(860, 40, 150, 14);

        SubjectField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectField3ActionPerformed(evt);
            }
        });
        jPanel1.add(SubjectField3);
        SubjectField3.setBounds(590, 110, 220, 30);

        SubjectField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectField4ActionPerformed(evt);
            }
        });
        jPanel1.add(SubjectField4);
        SubjectField4.setBounds(1020, 30, 160, 30);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(1020, 70, 160, 30);

        CommentaryLabel3.setText("Note! To let the application send emails, you have");
        CommentaryLabel3.setDoubleBuffered(true);
        jPanel1.add(CommentaryLabel3);
        CommentaryLabel3.setBounds(950, 160, 290, 20);

        CommentaryLabel4.setText("to allow less secure apps in google account. ");
        CommentaryLabel4.setDoubleBuffered(true);
        jPanel1.add(CommentaryLabel4);
        CommentaryLabel4.setBounds(960, 180, 270, 20);

        CommentaryLabel5.setBackground(new java.awt.Color(226, 226, 226));
        CommentaryLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CommentaryLabel5.setText("(click here to open the link)");
        CommentaryLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CommentaryLabel5.setDoubleBuffered(true);
        CommentaryLabel5.setOpaque(true);
        CommentaryLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CommentaryLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CommentaryLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CommentaryLabel5MouseExited(evt);
            }
        });
        jPanel1.add(CommentaryLabel5);
        CommentaryLabel5.setBounds(980, 210, 170, 40);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                String[] lines = EmailArea.getText().split("\\n");
                String Subject = SubjectField1.getText();
                String Message =  MessageArea1.getText();
                String email =  SubjectField4.getText();
                char[] passwordChar =  jPasswordField1.getPassword();
                String RepeatSubject = SubjectField3.getText();
                String RepeatMessage =  MessageArea2.getText();
                int count = Integer.valueOf(jLabel1.getText());

                for (int i = 0; i<Integer.parseInt(Number.getText()); i++){
                    for (int j = 0; j<lines.length; j++){ 
                    SendMailOrig.send(lines[j], Subject, Message, email, String.valueOf(passwordChar));
                    count++;                
                    jLabel1.setText(String.valueOf(count));                
                    jLabel1.setForeground(new java.awt.Color(49, 133, 15));
                    jLabel1.paintImmediately(jLabel1.getVisibleRect());


                    Message = Message + RepeatMessage;
                    Subject = Subject + RepeatSubject;
                    }
                
                
                //this.repaint();
                //this.revalidate();
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new java.awt.Color(255, 108, 108));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new java.awt.Color(255, 63, 63));
    }//GEN-LAST:event_jButton1MouseEntered

    private void SubjectField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubjectField3ActionPerformed

    private void SubjectField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubjectField4ActionPerformed

    private void CommentaryLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CommentaryLabel5MouseClicked
        if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
            try {
                Desktop.getDesktop().browse(new URI("https://myaccount.google.com/lesssecureapps"));
            } catch (URISyntaxException | IOException ex) {
//                Logger.getLogger(MailApp.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Seems like an URI problem lol");
            }
        }
    }//GEN-LAST:event_CommentaryLabel5MouseClicked

    private void CommentaryLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CommentaryLabel5MouseEntered
        CommentaryLabel5.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_CommentaryLabel5MouseEntered

    private void CommentaryLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CommentaryLabel5MouseExited
        CommentaryLabel5.setBackground(new java.awt.Color(226,226,226));

    }//GEN-LAST:event_CommentaryLabel5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MailApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MailApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MailApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MailApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MailApp().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CommentaryLabel3;
    private javax.swing.JLabel CommentaryLabel4;
    private javax.swing.JLabel CommentaryLabel5;
    private javax.swing.JTextArea EmailArea;
    private javax.swing.JTextArea MessageArea1;
    private javax.swing.JTextArea MessageArea2;
    private javax.swing.JTextField Number;
    private javax.swing.JTextField SubjectField1;
    private javax.swing.JTextField SubjectField3;
    private javax.swing.JTextField SubjectField4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
